### PR TITLE
get_unit_id

### PR DESCRIPTION
**Pull request by maier-m**
A function which allows users to quickly find eml unit ids from more common ways units are named. e.g. `get_unit_id("g/cm^3")` will return "gramsPerCubicCentimeter" or "gramPerCentimeterCubed" if eml schema is 2.2.0 or greater... Can possibly add to this to build custom units if returned unit id is not a standard unit

### CODE REVIEW

**Comment by cboettig** [comment]
@maier-m Nice, this looks really slick! Thanks for the vignette updates too.

**Comment by maier-m** [comment]
Yes I can update more of the vignette too but was realizing it hasn't been updated from EML package yet. I can help update more later on.

**Comment by cboettig** [comment]
Right, I've quarantined all the vignettes into `EML_vignettes` instead of the official `vignettes` until they get updated.  (I kinda updated `creating-EML.Rmd` but only as a quick minimal translation).

p.s. I just about have a working version of EML 2.2.0 in `emld`, if all goes well `eml2` should just be able to use `2.2.0` by setting `options(eml_db="eml-2.2.0")`, which will eventually be set by default.  

Would be good to add some helper utilities based on the new `2.2.0` features then, but will have to figure out how to handle backwards compatibility in that case.

**Comment by maier-m** [comment]
Yeah, I noticed the `eml_db` feature in the code. `get_unit_id` currently has a variable input of `eml_version` which defaults to `getOption("eml_db", "eml-2.2.0")`... needed as the naming for units is changing fairly significantly in eml-2.2.0

**Comment by cboettig** [comment]
minor postscript: no need to add a `units` to travis manually, it should get pulled in from SUGGESTS (of course you need to add the lib system dependencies but you did that already). see https://github.com/cboettig/eml2/pull/5

**Comment by cboettig** [comment]
@maier-m p.s. meant to say, can you add yourself at `ctb` in the DESCRIPTION too?

**Pull request merged**
